"""
Pydantic schemas for structured outputs across all agents.
These models enforce data contracts throughout the pipeline.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from enum import Enum
from datetime import datetime


class UrgencyLevel(str, Enum):
    EMERGENCY = "EMERGENCY"       # Life-threatening, 911/ER immediately
    URGENT = "URGENT"             # See doctor within hours
    SEMI_URGENT = "SEMI_URGENT"   # See doctor within 24–48 hours
    NON_URGENT = "NON_URGENT"     # Routine appointment


class Department(str, Enum):
    EMERGENCY = "Emergency Medicine"
    CARDIOLOGY = "Cardiology"
    NEUROLOGY = "Neurology"
    PULMONOLOGY = "Pulmonology / Respiratory"
    GASTROENTEROLOGY = "Gastroenterology"
    ORTHOPEDICS = "Orthopedics"
    GENERAL = "General Practice"
    PSYCHIATRY = "Psychiatry / Mental Health"
    DERMATOLOGY = "Dermatology"
    UROLOGY = "Urology"
    OB_GYN = "OB-GYN"
    PEDIATRICS = "Pediatrics"
    ENT = "ENT (Ear, Nose, Throat)"


class PatientDemographics(BaseModel):
    """Basic patient information collected at intake."""
    age: int = Field(..., ge=0, le=130, description="Patient age in years")
    sex: Literal["Male", "Female", "Other"]
    chief_complaint: str = Field(..., description="Primary reason for visit")


class SymptomDetail(BaseModel):
    """Structured representation of a reported symptom."""
    name: str
    duration: Optional[str] = None          # e.g. "3 days", "2 hours"
    severity: Optional[int] = None          # 1–10 scale
    onset: Optional[str] = None             # "sudden" or "gradual"
    associated_factors: Optional[str] = None


class IntakeState(BaseModel):
    """
    Full state object passed through the LangGraph workflow.
    Represents the complete patient intake session.
    """
    session_id: str
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    demographics: Optional[PatientDemographics] = None
    symptoms: List[SymptomDetail] = Field(default_factory=list)
    medical_history: Optional[str] = None
    current_medications: Optional[str] = None
    allergies: Optional[str] = None
    vital_signs: Optional[dict] = None     # Optional free-form vitals
    red_flags_detected: List[str] = Field(default_factory=list)
    intake_complete: bool = False
    critic_approved: bool = False
    escalation_triggered: bool = False
    iterations: int = 0                    # Track reflection loop count


class TriageDecision(BaseModel):
    """Output of the Triage Agent — urgency classification."""
    urgency_level: UrgencyLevel
    department: Department
    rationale: str = Field(..., description="Clinical reasoning for triage decision")
    confidence_score: float = Field(..., ge=0.0, le=1.0,
                                    description="Model confidence in the decision")
    rule_triggered: Optional[str] = None   # Name of hard rule if one fired
    recommended_actions: List[str] = Field(default_factory=list)
    estimated_wait: Optional[str] = None   # e.g. "Within 15 minutes"


class CriticFeedback(BaseModel):
    """Feedback from the Critic Agent after reviewing intake."""
    approved: bool
    missed_red_flags: List[str] = Field(default_factory=list)
    suggested_questions: List[str] = Field(default_factory=list)
    critique_notes: str = ""


class MedicalSummary(BaseModel):
    """
    Final structured medical briefing generated by the Synthesis Agent.
    This is the output shown to the clinician.
    """
    session_id: str
    generated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    patient_snapshot: str       # 1–2 sentence patient overview
    symptom_analysis: str       # Detailed symptom interpretation
    differential_considerations: List[str]   # Possible diagnoses (NOT definitive)
    triage_decision: TriageDecision
    red_flag_alerts: List[str] = Field(default_factory=list)
    recommended_workup: List[str] = Field(default_factory=list)
    clinician_notes: str        # Free-text notes for receiving clinician
    disclaimer: str = (
        "⚠️ This is a clinical decision support prototype. "
        "Not a substitute for professional medical judgment. "
        "Always verify with a licensed clinician."
    )
